[build]
  command = "npm run build:prod"
  publish = "dist/client"
  
[build.environment]
  NODE_VERSION = "20"
  BUILD_TIME = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "dist/analog/server"
  node_bundler = "esbuild"
